export interface Business {
  id: string
  name: string
  description: string
  category: string
  subcategory?: string
  location: string
  country: string
  rating: number
  reviews: number
  image: string
  verified: boolean
  established: number
  employees: string
  website?: string
  phone?: string
  email?: string
  products: string[]
  certifications: string[]
  minOrderValue: string
  paymentTerms: string[]
  shippingMethods: string[]
  responseTime: string
  businessType: "supplier" | "manufacturer" | "trader" | "service_provider"
  tags: string[]
}

export const mockBusinesses: Business[] = [
  {
    id: "1",
    name: "Global Tech Solutions",
    description:
      "Leading provider of enterprise software solutions and IT consulting services with over 15 years of experience in digital transformation.",
    category: "Computers & Technology",
    subcategory: "Software Development",
    location: "New York, USA",
    country: "United States",
    rating: 4.8,
    reviews: 234,
    image: "/modern-tech-office.png",
    verified: true,
    established: 2008,
    employees: "500-1000",
    website: "https://globaltechsolutions.com",
    phone: "+1-555-0101",
    email: "contact@globaltechsolutions.com",
    products: ["Enterprise Software", "Cloud Solutions", "Mobile Apps", "AI/ML Services"],
    certifications: ["ISO 27001", "SOC 2", "AWS Partner"],
    minOrderValue: "$10,000",
    paymentTerms: ["Net 30", "Credit Card", "Wire Transfer"],
    shippingMethods: ["Digital Delivery", "On-site Installation"],
    responseTime: "Within 2 hours",
    businessType: "service_provider",
    tags: ["technology", "software", "enterprise", "cloud", "AI"],
  },
  {
    id: "2",
    name: "Premium Textiles Co.",
    description:
      "High-quality textile manufacturing with sustainable practices and global reach. Specializing in organic cotton and eco-friendly fabrics.",
    category: "Textiles & Garments",
    subcategory: "Fabric Manufacturing",
    location: "Mumbai, India",
    country: "India",
    rating: 4.6,
    reviews: 189,
    image: "/placeholder-oxojy.png",
    verified: true,
    established: 1995,
    employees: "1000-5000",
    website: "https://premiumtextiles.in",
    phone: "+91-22-1234-5678",
    email: "export@premiumtextiles.in",
    products: ["Organic Cotton", "Silk Fabrics", "Denim", "Technical Textiles"],
    certifications: ["GOTS", "OEKO-TEX", "ISO 14001"],
    minOrderValue: "$5,000",
    paymentTerms: ["L/C", "T/T", "D/P"],
    shippingMethods: ["Sea Freight", "Air Freight", "Express Courier"],
    responseTime: "Within 4 hours",
    businessType: "manufacturer",
    tags: ["textiles", "organic", "sustainable", "cotton", "export"],
  },
  {
    id: "3",
    name: "Fresh Farm Exports",
    description:
      "Organic produce supplier specializing in fresh fruits and vegetables export with farm-to-table traceability.",
    category: "Agriculture & Food",
    subcategory: "Fresh Produce",
    location: "California, USA",
    country: "United States",
    rating: 4.9,
    reviews: 156,
    image: "/modern-agricultural-farm.png",
    verified: true,
    established: 2010,
    employees: "100-500",
    website: "https://freshfarmexports.com",
    phone: "+1-559-123-4567",
    email: "sales@freshfarmexports.com",
    products: ["Organic Fruits", "Fresh Vegetables", "Herbs", "Nuts"],
    certifications: ["USDA Organic", "GlobalGAP", "Fair Trade"],
    minOrderValue: "$2,000",
    paymentTerms: ["Net 15", "Credit Card", "L/C"],
    shippingMethods: ["Refrigerated Truck", "Air Freight", "Cold Chain"],
    responseTime: "Within 1 hour",
    businessType: "supplier",
    tags: ["organic", "fresh", "agriculture", "export", "sustainable"],
  },
  {
    id: "4",
    name: "BuildRight Materials",
    description:
      "Premium construction materials and building supplies for large-scale projects with nationwide distribution network.",
    category: "Construction Materials",
    subcategory: "Building Supplies",
    location: "Dubai, UAE",
    country: "United Arab Emirates",
    rating: 4.7,
    reviews: 298,
    image: "/construction-warehouse.png",
    verified: true,
    established: 2005,
    employees: "500-1000",
    website: "https://buildrightmaterials.ae",
    phone: "+971-4-123-4567",
    email: "info@buildrightmaterials.ae",
    products: ["Steel", "Cement", "Tiles", "Insulation Materials"],
    certifications: ["ISO 9001", "CE Marking", "Emirates Quality Mark"],
    minOrderValue: "$15,000",
    paymentTerms: ["Net 30", "L/C", "Bank Guarantee"],
    shippingMethods: ["Truck", "Container", "Bulk Carrier"],
    responseTime: "Within 3 hours",
    businessType: "supplier",
    tags: ["construction", "building", "materials", "steel", "cement"],
  },
  {
    id: "5",
    name: "EcoChemicals Ltd",
    description:
      "Sustainable chemical solutions for industrial applications with focus on environmental responsibility.",
    category: "Chemicals & Minerals",
    subcategory: "Industrial Chemicals",
    location: "Hamburg, Germany",
    country: "Germany",
    rating: 4.5,
    reviews: 167,
    image: "/chemical-plant.png",
    verified: true,
    established: 2000,
    employees: "200-500",
    website: "https://ecochemicals.de",
    phone: "+49-40-123-4567",
    email: "sales@ecochemicals.de",
    products: ["Green Solvents", "Bio-based Chemicals", "Catalysts", "Specialty Chemicals"],
    certifications: ["REACH", "ISO 14001", "Responsible Care"],
    minOrderValue: "$8,000",
    paymentTerms: ["Net 30", "L/C", "SEPA"],
    shippingMethods: ["Tank Truck", "ISO Tank", "Drums"],
    responseTime: "Within 6 hours",
    businessType: "manufacturer",
    tags: ["chemicals", "sustainable", "industrial", "green", "specialty"],
  },
  {
    id: "6",
    name: "Digital Learning Hub",
    description: "Educational technology solutions and e-learning platforms for schools and corporate training.",
    category: "Books & Education",
    subcategory: "E-Learning",
    location: "London, UK",
    country: "United Kingdom",
    rating: 4.4,
    reviews: 143,
    image: "/modern-classroom.png",
    verified: true,
    established: 2015,
    employees: "50-100",
    website: "https://digitallearninghub.co.uk",
    phone: "+44-20-1234-5678",
    email: "hello@digitallearninghub.co.uk",
    products: ["LMS Platforms", "Educational Apps", "VR Learning", "Assessment Tools"],
    certifications: ["ISO 27001", "GDPR Compliant", "EdTech UK"],
    minOrderValue: "$3,000",
    paymentTerms: ["Net 30", "Credit Card", "Direct Debit"],
    shippingMethods: ["Digital Delivery", "Cloud Deployment"],
    responseTime: "Within 2 hours",
    businessType: "service_provider",
    tags: ["education", "technology", "e-learning", "digital", "training"],
  },
  {
    id: "7",
    name: "MedEquip Solutions",
    description:
      "Medical equipment and surgical instruments supplier with global distribution and after-sales support.",
    category: "Health & Medical",
    subcategory: "Medical Equipment",
    location: "Singapore",
    country: "Singapore",
    rating: 4.8,
    reviews: 201,
    image: "/medical-equipment-warehouse.png",
    verified: true,
    established: 2012,
    employees: "100-200",
    website: "https://medequipsolutions.sg",
    phone: "+65-6123-4567",
    email: "sales@medequipsolutions.sg",
    products: ["Surgical Instruments", "Diagnostic Equipment", "Hospital Furniture", "PPE"],
    certifications: ["ISO 13485", "CE Mark", "FDA Approved"],
    minOrderValue: "$5,000",
    paymentTerms: ["Net 30", "L/C", "T/T"],
    shippingMethods: ["Air Freight", "Sea Freight", "Express"],
    responseTime: "Within 1 hour",
    businessType: "supplier",
    tags: ["medical", "healthcare", "surgical", "equipment", "certified"],
  },
  {
    id: "8",
    name: "AutoParts Global",
    description: "Automotive parts and accessories distributor serving dealerships and repair shops worldwide.",
    category: "Automotive",
    subcategory: "Auto Parts",
    location: "Detroit, USA",
    country: "United States",
    rating: 4.3,
    reviews: 312,
    image: "/automotive-parts-warehouse.png",
    verified: true,
    established: 1998,
    employees: "200-500",
    website: "https://autopartsglobal.com",
    phone: "+1-313-123-4567",
    email: "orders@autopartsglobal.com",
    products: ["Engine Parts", "Brake Systems", "Electronics", "Body Parts"],
    certifications: ["ISO/TS 16949", "IATF 16949", "OEM Certified"],
    minOrderValue: "$1,000",
    paymentTerms: ["Net 30", "Credit Card", "COD"],
    shippingMethods: ["Ground", "Air", "LTL Freight"],
    responseTime: "Within 30 minutes",
    businessType: "supplier",
    tags: ["automotive", "parts", "OEM", "aftermarket", "global"],
  },
]

export const categories = [
  {
    name: "Agriculture & Food",
    slug: "agriculture-food",
    icon: "🌾",
    count: 2450,
    subcategories: ["Fresh Produce", "Processed Foods", "Beverages", "Agricultural Equipment", "Seeds & Plants"],
    products: [
      {
        id: "agri-1",
        name: "Organic Wheat",
        price: "$450/ton",
        supplier: "Fresh Farm Exports",
        image: "/organic-wheat.png",
      },
      {
        id: "agri-2",
        name: "Premium Rice",
        price: "$680/ton",
        supplier: "Asian Grains Co.",
        image: "/premium-rice.png",
      },
      {
        id: "agri-3",
        name: "Fresh Apples",
        price: "$1200/ton",
        supplier: "Orchard Direct",
        image: "/fresh-apples.png",
      },
      {
        id: "agri-4",
        name: "Coffee Beans",
        price: "$3500/ton",
        supplier: "Mountain Coffee",
        image: "/coffee-beans.png",
      },
    ],
  },
  {
    name: "Builders & Real Estate",
    slug: "builders-real-estate",
    icon: "🏗️",
    count: 1890,
    subcategories: [
      "Construction Services",
      "Real Estate Development",
      "Architecture",
      "Interior Design",
      "Property Management",
    ],
    products: [
      {
        id: "build-1",
        name: "Steel Beams",
        price: "$850/ton",
        supplier: "BuildRight Materials",
        image: "/steel-beams.png",
      },
      {
        id: "build-2",
        name: "Concrete Blocks",
        price: "$45/m³",
        supplier: "Concrete Solutions",
        image: "/concrete-blocks.png",
      },
      { id: "build-3", name: "Roofing Tiles", price: "$25/m²", supplier: "Roof Masters", image: "/roofing-tiles.png" },
      {
        id: "build-4",
        name: "Insulation Foam",
        price: "$35/m²",
        supplier: "Thermal Pro",
        image: "/insulation-foam.png",
      },
    ],
  },
  {
    name: "Books & Education",
    slug: "books-education",
    icon: "📚",
    count: 1234,
    subcategories: [
      "Educational Books",
      "E-Learning",
      "Training Services",
      "Educational Technology",
      "Academic Publishing",
    ],
    products: [
      {
        id: "edu-1",
        name: "LMS Platform",
        price: "$299/month",
        supplier: "Digital Learning Hub",
        image: "/lms-platform.png",
      },
      {
        id: "edu-2",
        name: "VR Training Kit",
        price: "$2500/unit",
        supplier: "EduTech Solutions",
        image: "/vr-training.png",
      },
      {
        id: "edu-3",
        name: "Interactive Whiteboard",
        price: "$1200/unit",
        supplier: "Smart Classroom",
        image: "/interactive-board.png",
      },
      {
        id: "edu-4",
        name: "Educational Software",
        price: "$150/license",
        supplier: "LearnSoft Inc",
        image: "/edu-software.png",
      },
    ],
  },
  {
    name: "Business Services & Others",
    slug: "business-services",
    icon: "💼",
    count: 3567,
    subcategories: ["Consulting", "Marketing", "Legal Services", "Accounting", "HR Services"],
    products: [
      {
        id: "biz-1",
        name: "Business Consulting",
        price: "$200/hour",
        supplier: "Strategy Partners",
        image: "/consulting.png",
      },
      {
        id: "biz-2",
        name: "Digital Marketing",
        price: "$5000/month",
        supplier: "Growth Agency",
        image: "/digital-marketing.png",
      },
      {
        id: "biz-3",
        name: "Legal Advisory",
        price: "$350/hour",
        supplier: "Corporate Law Firm",
        image: "/legal-services.png",
      },
      {
        id: "biz-4",
        name: "HR Management",
        price: "$150/employee",
        supplier: "People Solutions",
        image: "/hr-services.png",
      },
    ],
  },
  {
    name: "Chemicals & Minerals",
    slug: "chemicals-minerals",
    icon: "⚗️",
    count: 987,
    subcategories: ["Industrial Chemicals", "Specialty Chemicals", "Mining", "Petrochemicals", "Laboratory Chemicals"],
    products: [
      {
        id: "chem-1",
        name: "Industrial Solvent",
        price: "$1200/ton",
        supplier: "EcoChemicals Ltd",
        image: "/industrial-solvent.png",
      },
      { id: "chem-2", name: "Specialty Catalyst", price: "$8500/kg", supplier: "ChemTech Pro", image: "/catalyst.png" },
      {
        id: "chem-3",
        name: "Laboratory Reagent",
        price: "$450/liter",
        supplier: "Lab Supplies Co",
        image: "/reagent.png",
      },
      {
        id: "chem-4",
        name: "Mining Chemicals",
        price: "$2200/ton",
        supplier: "Mine Solutions",
        image: "/mining-chemicals.png",
      },
    ],
  },
  {
    name: "Construction, Material & Scrap",
    slug: "construction-materials",
    icon: "🧱",
    count: 2123,
    subcategories: ["Building Supplies", "Steel & Metal", "Cement & Concrete", "Insulation", "Roofing Materials"],
    products: [
      {
        id: "const-1",
        name: "Recycled Steel",
        price: "$650/ton",
        supplier: "Scrap Metal Co",
        image: "/recycled-steel.png",
      },
      { id: "const-2", name: "Cement Mix", price: "$85/ton", supplier: "Concrete Masters", image: "/cement-mix.png" },
      {
        id: "const-3",
        name: "Aluminum Scrap",
        price: "$1800/ton",
        supplier: "Metal Recyclers",
        image: "/aluminum-scrap.png",
      },
      {
        id: "const-4",
        name: "Construction Sand",
        price: "$25/ton",
        supplier: "Aggregate Supply",
        image: "/construction-sand.png",
      },
    ],
  },
  {
    name: "Computers, IT & Telecommunications",
    slug: "computers-technology",
    icon: "💻",
    count: 4567,
    subcategories: ["Software Development", "Hardware", "IT Services", "Telecommunications", "Electronics"],
    products: [
      {
        id: "tech-1",
        name: "Enterprise Software",
        price: "$50000/license",
        supplier: "Global Tech Solutions",
        image: "/enterprise-software.png",
      },
      {
        id: "tech-2",
        name: "Server Hardware",
        price: "$8500/unit",
        supplier: "TechHardware Pro",
        image: "/server-hardware.png",
      },
      {
        id: "tech-3",
        name: "Network Equipment",
        price: "$3200/unit",
        supplier: "NetSolutions Inc",
        image: "/network-equipment.png",
      },
      {
        id: "tech-4",
        name: "Cloud Services",
        price: "$500/month",
        supplier: "CloudTech Ltd",
        image: "/cloud-services.png",
      },
    ],
  },
  {
    name: "Energy",
    slug: "energy",
    icon: "⚡",
    count: 1456,
    subcategories: ["Solar Energy", "Wind Power", "Oil & Gas", "Battery Technology", "Energy Storage"],
    products: [
      {
        id: "energy-1",
        name: "Solar Panels",
        price: "$250/panel",
        supplier: "SolarTech Solutions",
        image: "/solar-panels.png",
      },
      {
        id: "energy-2",
        name: "Wind Turbine",
        price: "$2.5M/unit",
        supplier: "WindPower Corp",
        image: "/wind-turbine.png",
      },
      {
        id: "energy-3",
        name: "Lithium Battery",
        price: "$450/kWh",
        supplier: "Battery Innovations",
        image: "/lithium-battery.png",
      },
      {
        id: "energy-4",
        name: "Energy Storage",
        price: "$1200/kWh",
        supplier: "PowerStore Ltd",
        image: "/energy-storage.png",
      },
    ],
  },
  {
    name: "Excess Inventory",
    slug: "excess-inventory",
    icon: "📦",
    count: 892,
    subcategories: ["Overstock Items", "Liquidation", "Surplus Equipment", "Closeout Deals", "Bulk Sales"],
    products: [
      {
        id: "excess-1",
        name: "Electronics Overstock",
        price: "$50-200/unit",
        supplier: "Liquidation Pros",
        image: "/electronics-overstock.png",
      },
      {
        id: "excess-2",
        name: "Textile Surplus",
        price: "$5-15/yard",
        supplier: "Fabric Liquidators",
        image: "/textile-surplus.png",
      },
      {
        id: "excess-3",
        name: "Machinery Surplus",
        price: "$5000-50000/unit",
        supplier: "Equipment Liquidation",
        image: "/machinery-surplus.png",
      },
      {
        id: "excess-4",
        name: "Consumer Goods",
        price: "$10-100/unit",
        supplier: "Overstock Outlet",
        image: "/consumer-goods.png",
      },
    ],
  },
  {
    name: "Foreign Companies",
    slug: "foreign-companies",
    icon: "🌍",
    count: 2341,
    subcategories: [
      "Import/Export",
      "International Trade",
      "Global Sourcing",
      "Cross-border Commerce",
      "Trade Finance",
    ],
    products: [
      {
        id: "foreign-1",
        name: "Import Services",
        price: "$500-2000/shipment",
        supplier: "Global Trade Partners",
        image: "/import-services.png",
      },
      {
        id: "foreign-2",
        name: "Export Documentation",
        price: "$200-500/order",
        supplier: "Trade Docs Pro",
        image: "/export-docs.png",
      },
      {
        id: "foreign-3",
        name: "Customs Clearance",
        price: "$300-800/shipment",
        supplier: "Customs Solutions",
        image: "/customs-clearance.png",
      },
      {
        id: "foreign-4",
        name: "Trade Finance",
        price: "2-5% of value",
        supplier: "International Bank",
        image: "/trade-finance.png",
      },
    ],
  },
  {
    name: "Health, Lab & Surgical Items",
    slug: "health-medical",
    icon: "🏥",
    count: 1876,
    subcategories: ["Medical Equipment", "Pharmaceuticals", "Healthcare Services", "Dental", "Veterinary"],
    products: [
      {
        id: "med-1",
        name: "Surgical Instruments",
        price: "$150-500/set",
        supplier: "MedEquip Solutions",
        image: "/surgical-instruments.png",
      },
      {
        id: "med-2",
        name: "Diagnostic Equipment",
        price: "$25000-100000/unit",
        supplier: "MedTech Innovations",
        image: "/diagnostic-equipment.png",
      },
      {
        id: "med-3",
        name: "Laboratory Supplies",
        price: "$50-200/kit",
        supplier: "LabSupply Pro",
        image: "/lab-supplies.png",
      },
      {
        id: "med-4",
        name: "Hospital Furniture",
        price: "$500-5000/unit",
        supplier: "Healthcare Furniture",
        image: "/hospital-furniture.png",
      },
    ],
  },
  {
    name: "House Hold Furnitures & Appliances",
    slug: "furniture-appliances",
    icon: "🪑",
    count: 1654,
    subcategories: ["Home Furniture", "Kitchen Appliances", "Electronics", "Home Decor", "Outdoor Furniture"],
    products: [
      {
        id: "home-1",
        name: "Office Furniture Set",
        price: "$800-2500/set",
        supplier: "Furniture Solutions",
        image: "/office-furniture.png",
      },
      {
        id: "home-2",
        name: "Kitchen Appliances",
        price: "$200-1500/unit",
        supplier: "Home Appliance Co",
        image: "/kitchen-appliances.png",
      },
      {
        id: "home-3",
        name: "Living Room Set",
        price: "$1200-4000/set",
        supplier: "Comfort Living",
        image: "/living-room-set.png",
      },
      {
        id: "home-4",
        name: "Smart Home Devices",
        price: "$50-500/unit",
        supplier: "Smart Home Tech",
        image: "/smart-home.png",
      },
    ],
  },
  {
    name: "Islamic Products",
    slug: "islamic-products",
    icon: "🕌",
    count: 567,
    subcategories: ["Halal Food", "Islamic Books", "Prayer Items", "Islamic Clothing", "Religious Artifacts"],
    products: [
      {
        id: "islamic-1",
        name: "Halal Meat Products",
        price: "$8-15/kg",
        supplier: "Halal Foods International",
        image: "/halal-meat.png",
      },
      {
        id: "islamic-2",
        name: "Prayer Rugs",
        price: "$25-150/unit",
        supplier: "Islamic Crafts",
        image: "/prayer-rugs.png",
      },
      {
        id: "islamic-3",
        name: "Islamic Books",
        price: "$10-50/book",
        supplier: "Islamic Publishing",
        image: "/islamic-books.png",
      },
      {
        id: "islamic-4",
        name: "Modest Clothing",
        price: "$30-200/piece",
        supplier: "Modest Fashion Co",
        image: "/modest-clothing.png",
      },
    ],
  },
  {
    name: "Plant & Machinery",
    slug: "plant-machinery",
    icon: "🏭",
    count: 1234,
    subcategories: [
      "Industrial Equipment",
      "Manufacturing Machinery",
      "Construction Equipment",
      "Agricultural Machinery",
      "Mining Equipment",
    ],
    products: [
      {
        id: "machine-1",
        name: "CNC Machine",
        price: "$50000-200000/unit",
        supplier: "Precision Machinery",
        image: "/cnc-machine.png",
      },
      {
        id: "machine-2",
        name: "Excavator",
        price: "$80000-300000/unit",
        supplier: "Heavy Equipment Co",
        image: "/excavator.png",
      },
      {
        id: "machine-3",
        name: "Industrial Printer",
        price: "$15000-75000/unit",
        supplier: "Print Solutions",
        image: "/industrial-printer.png",
      },
      {
        id: "machine-4",
        name: "Packaging Machine",
        price: "$25000-100000/unit",
        supplier: "Pack Tech Industries",
        image: "/packaging-machine.png",
      },
    ],
  },
  {
    name: "Printing & Packaging",
    slug: "printing-packaging",
    icon: "📦",
    count: 987,
    subcategories: [
      "Commercial Printing",
      "Packaging Materials",
      "Labels & Stickers",
      "Promotional Items",
      "Custom Packaging",
    ],
    products: [
      {
        id: "print-1",
        name: "Custom Packaging Boxes",
        price: "$0.50-5.00/unit",
        supplier: "PackPro Solutions",
        image: "/custom-boxes.png",
      },
      {
        id: "print-2",
        name: "Commercial Printing",
        price: "$0.05-2.00/page",
        supplier: "Print Masters",
        image: "/commercial-printing.png",
      },
      {
        id: "print-3",
        name: "Product Labels",
        price: "$0.10-1.00/label",
        supplier: "Label Experts",
        image: "/product-labels.png",
      },
      {
        id: "print-4",
        name: "Promotional Items",
        price: "$1.00-25.00/unit",
        supplier: "Promo Products Inc",
        image: "/promotional-items.png",
      },
    ],
  },
  {
    name: "Plastic & Rubber",
    slug: "plastic-rubber",
    icon: "🔧",
    count: 1456,
    subcategories: [
      "Plastic Raw Materials",
      "Rubber Products",
      "Molded Parts",
      "Plastic Packaging",
      "Industrial Plastics",
    ],
    products: [
      {
        id: "plastic-1",
        name: "Plastic Pellets",
        price: "$800-1500/ton",
        supplier: "Polymer Solutions",
        image: "/plastic-pellets.png",
      },
      {
        id: "plastic-2",
        name: "Rubber Sheets",
        price: "$5-25/m²",
        supplier: "Rubber Industries",
        image: "/rubber-sheets.png",
      },
      {
        id: "plastic-3",
        name: "Molded Components",
        price: "$2-50/unit",
        supplier: "Precision Molding",
        image: "/molded-components.png",
      },
      {
        id: "plastic-4",
        name: "Plastic Containers",
        price: "$0.50-10.00/unit",
        supplier: "Container Corp",
        image: "/plastic-containers.png",
      },
    ],
  },
  {
    name: "Sports Products & Services",
    slug: "sports-products",
    icon: "⚽",
    count: 789,
    subcategories: ["Sports Equipment", "Fitness Gear", "Outdoor Recreation", "Team Sports", "Athletic Apparel"],
    products: [
      {
        id: "sports-1",
        name: "Fitness Equipment",
        price: "$200-5000/unit",
        supplier: "FitPro Equipment",
        image: "/fitness-equipment.png",
      },
      {
        id: "sports-2",
        name: "Sports Uniforms",
        price: "$25-100/set",
        supplier: "Team Gear Co",
        image: "/sports-uniforms.png",
      },
      {
        id: "sports-3",
        name: "Outdoor Gear",
        price: "$50-500/unit",
        supplier: "Adventure Outfitters",
        image: "/outdoor-gear.png",
      },
      {
        id: "sports-4",
        name: "Athletic Shoes",
        price: "$30-200/pair",
        supplier: "Sports Footwear Inc",
        image: "/athletic-shoes.png",
      },
    ],
  },
  {
    name: "Startups",
    slug: "startups",
    icon: "🚀",
    count: 2341,
    subcategories: [
      "Tech Startups",
      "Innovation Services",
      "Startup Consulting",
      "Venture Capital",
      "Incubation Services",
    ],
    products: [
      {
        id: "startup-1",
        name: "MVP Development",
        price: "$10000-50000/project",
        supplier: "Startup Solutions",
        image: "/mvp-development.png",
      },
      {
        id: "startup-2",
        name: "Business Plan Service",
        price: "$2000-10000/plan",
        supplier: "Strategy Consultants",
        image: "/business-plan.png",
      },
      {
        id: "startup-3",
        name: "Pitch Deck Design",
        price: "$1500-5000/deck",
        supplier: "Presentation Pros",
        image: "/pitch-deck.png",
      },
      {
        id: "startup-4",
        name: "Legal Setup Service",
        price: "$3000-15000/setup",
        supplier: "Startup Legal",
        image: "/legal-setup.png",
      },
    ],
  },
  {
    name: "Travel, Tourism & Sports",
    slug: "travel-tourism",
    icon: "✈️",
    count: 1567,
    subcategories: ["Travel Services", "Tourism Packages", "Hotel Booking", "Transportation", "Event Management"],
    products: [
      {
        id: "travel-1",
        name: "Corporate Travel",
        price: "$500-2000/trip",
        supplier: "Business Travel Co",
        image: "/corporate-travel.png",
      },
      {
        id: "travel-2",
        name: "Tourism Packages",
        price: "$800-5000/package",
        supplier: "Adventure Tours",
        image: "/tourism-packages.png",
      },
      {
        id: "travel-3",
        name: "Event Planning",
        price: "$2000-20000/event",
        supplier: "Event Masters",
        image: "/event-planning.png",
      },
      {
        id: "travel-4",
        name: "Transportation Services",
        price: "$50-500/day",
        supplier: "Transport Solutions",
        image: "/transportation.png",
      },
    ],
  },
  {
    name: "Women Led Businesses",
    slug: "women-led-businesses",
    icon: "👩‍💼",
    count: 1890,
    subcategories: [
      "Women Entrepreneurs",
      "Female-Owned Businesses",
      "Women's Products",
      "Empowerment Services",
      "Diversity Suppliers",
    ],
    products: [
      {
        id: "women-1",
        name: "Handcrafted Products",
        price: "$15-150/unit",
        supplier: "Women Artisans Co",
        image: "/handcrafted-products.png",
      },
      {
        id: "women-2",
        name: "Beauty Products",
        price: "$10-100/unit",
        supplier: "Natural Beauty Co",
        image: "/beauty-products.png",
      },
      {
        id: "women-3",
        name: "Professional Services",
        price: "$100-500/hour",
        supplier: "Women Professionals",
        image: "/professional-services.png",
      },
      {
        id: "women-4",
        name: "Fashion Accessories",
        price: "$20-200/unit",
        supplier: "Style Entrepreneurs",
        image: "/fashion-accessories.png",
      },
    ],
  },
  {
    name: "Others",
    slug: "others",
    icon: "📋",
    count: 3456,
    subcategories: ["Miscellaneous", "General Services", "Specialty Items", "Custom Solutions", "Unique Products"],
    products: [
      {
        id: "other-1",
        name: "Custom Solutions",
        price: "Quote on Request",
        supplier: "Solution Providers",
        image: "/custom-solutions.png",
      },
      {
        id: "other-2",
        name: "Specialty Services",
        price: "$200-1000/service",
        supplier: "Specialty Experts",
        image: "/specialty-services.png",
      },
      {
        id: "other-3",
        name: "Unique Products",
        price: "$50-500/unit",
        supplier: "Innovation Hub",
        image: "/unique-products.png",
      },
      {
        id: "other-4",
        name: "General Supplies",
        price: "$10-200/unit",
        supplier: "General Supply Co",
        image: "/general-supplies.png",
      },
    ],
  },
]
